github and azdo code for webapps

diff --git a/.github/actions/prepare_docker_image/action.yml b/.github/actions/prepare_docker_image/action.yml
--- a/.github/actions/prepare_docker_image/action.yml
+++ b/.github/actions/prepare_docker_image/action.yml
@@ -1,28 +1,86 @@
-name: kubernetes_deployment
+name: prep_docker_image
 
-description: execute an online endpoint for real time inference
+description: Creates a new docker images for PF deployment
 
 inputs:
-  flow_to_execute:
+  FLOW_TO_EXECUTE:
     description: "the flow to be registered and deployed"
     required: true
   DEPLOY_ENVIRONMENT:
     description: "env stage e.g. dev, test, prod"
     required: true
   CONNECTION_DETAILS:
-    description: "PF connection details"
-    required: false
+    description: "pf connection details"
+    required: true
+  REGISTRY_DETAILS:
+    description: "docker image registry details"
+    required: true
 
 
 runs:
   using: composite
   steps:
-    - name: create local connections
-      uses: ./.github/actions/execute_script
-      with:
-        step_name: "Create local PF connections"
-        script_parameter: |
-          python -m llmops.common.prompt_local_aoai_connection \
-            --env_name ${{ inputs.DEPLOY_ENVIRONMENT }} \
-            --flow_to_execute ${{ inputs.flow_to_execute }} \
-            --connection_details '${{ inputs.CONNECTION_DETAILS }}'
+    - name: create docker image
+      run: |
+       set -e # fail on error
+       config_path="./${{ github.event.inputs.FLOW_TO_EXECUTE }}/llmops_config.json"
+       env_name=${{ github.event.inputs.DEPLOY_ENVIRONMENT }}
+       selected_object=$(jq ".envs[] | select(.ENV_NAME == \"$env_name\")" "$config_path")
+
+       if [[ -n "$selected_object" ]]; then
+         STANDARD_FLOW=$(echo "$selected_object" | jq -r '.STANDARD_FLOW_PATH')
+        
+         pf flow build --source "./${{ github.event.inputs.FLOW_TO_EXECUTE }}/$STANDARD_FLOW" --output "./${{ github.event.inputs.FLOW_TO_EXECUTE }}/docker"  --format docker 
+
+         mv "./${{ github.event.inputs.FLOW_TO_EXECUTE }}/environment/Dockerfile" "./${{ github.event.inputs.FLOW_TO_EXECUTE }}/docker/Dockerfile"
+
+         docker build -t localpf "./${{ github.event.inputs.FLOW_TO_EXECUTE }}/docker" --no-cache
+        
+         docker images
+
+         deploy_config="./${{ github.event.inputs.FLOW_TO_EXECUTE }}/configs/deployment_config.json"
+         con_object=$(jq ".webapp_endpoint[] | select(.ENV_NAME == \"$env_name\")" "$deploy_config")
+
+         read -r -a connection_names <<< "$(echo "$con_object" | jq -r '.CONNECTION_NAMES | join(" ")')"
+         echo $connection_names
+         result_string=""
+
+         for name in "${connection_names[@]}"; do
+            api_key=$(echo '${{ github.event.inputs.CONNECTION_DETAILS }}' | jq -r --arg name "$name" '.[] | select(.name == $name) | .api_key')
+            uppercase_name="${name^^}"
+            modified_name="${uppercase_name}_API_KEY"
+            result_string+=" -e $modified_name=$api_key"
+         done
+
+         IFS=' ' read -r -a docker_args <<< "$result_string"
+         docker_args+=(-m 512m --memory-reservation=256m --cpus=2 -dp 8080:8080 localpf:latest )
+         docker run "${docker_args[@]}"
+
+         sleep 15
+
+         docker ps -a
+        
+         chmod +x "./${{ github.event.inputs.FLOW_TO_EXECUTE }}/sample-request.json" 
+        
+         file_contents=$(<./${{ github.event.inputs.FLOW_TO_EXECUTE }}/sample-request.json)
+         echo "$file_contents"
+        
+         python -m llmops.common.deployment.test_local_flow \
+                 --flow_to_execute ${{ github.event.inputs.FLOW_TO_EXECUTE }}
+
+         REGISTRY_NAME=$(echo "$con_object" | jq -r '.REGISTRY_NAME')
+
+         registry_object=$(echo '${{ github.event.inputs.REGISTRY_DETAILS }}' | jq -r --arg name "$REGISTRY_NAME" '.[] | select(.registry_name == $name)')
+         register_server=$(echo "$registry_object" | jq -r '.register_server')
+         registry_username=$(echo "$registry_object" | jq -r '.registry_username')
+         registry_password=$(echo "$registry_object" | jq -r '.registry_password')
+
+
+         docker login "$register_server" -u "$registry_username" --password-stdin <<< "$registry_password" 
+         docker tag localpf "$register_server"/${{ github.event.inputs.FLOW_TO_EXECUTE }}_${{ github.event.inputs.DEPLOY_ENVIRONMENT }}:$(Build.BuildNumber)
+         docker push "$register_server"/${{ github.event.inputs.FLOW_TO_EXECUTE }}_${{ github.event.inputs.DEPLOY_ENVIRONMENT }}:$(Build.BuildNumber)
+        
+       else
+         echo "Object in config file not found"
+       fi
+
diff --git a/.github/actions/webapp_deployment/action.yml b/.github/actions/webapp_deployment/action.yml
--- a/.github/actions/webapp_deployment/action.yml
+++ b/.github/actions/webapp_deployment/action.yml
@@ -3,13 +3,18 @@ name: webapp_deployment
 description: deploys container on webapp
 
 inputs:
-  flow_to_execute:
+  FLOW_TO_EXECUTE:
     description: "the flow to be registered and deployed"
     required: true
   DEPLOY_ENVIRONMENT:
     description: "env stage e.g. dev, test, prod"
     required: true
-
+  CONNECTION_DETAILS:
+    description: "pf connection details"
+    required: true
+  REGISTRY_DETAILS:
+    description: "docker image registry details"
+    required: true
 
 runs:
   using: composite
@@ -17,6 +22,62 @@ runs:
     - name: prepare docker image
       uses: ./.github/actions/prepare_docker_image
       with:
-        flow_to_execute: ${{ inputs.flow_to_execute }}
-        DEPLOY_ENVIRONMENT: ${{ inputs.DEPLOY_ENVIRONMENT }}
-        connection_details: "${{ env.connection_details }}"
+        CONNECTION_DETAILS: ${{ inputs.connection_details }}
+        FLOW_TO_EXECUTE: ${{ inputs.flow_type }}
+        DEPLOY_ENVIRONMENT: ${{ inputs.env_name }}
+        REGISTRY_DETAILS: ${{ inputs.registry_details }}
+
+    - name: create docker image
+      run: |
+        set -e # fail on error
+        env_name=${{ github.event.inputs.DEPLOY_ENVIRONMENT }}
+        deploy_config="./${{ github.event.inputs.FLOW_TO_EXECUTE }}/configs/deployment_config.json"
+        con_object=$(jq ".webapp_endpoint[] | select(.ENV_NAME == \"$env_name\")" "$deploy_config")
+        REGISTRY_NAME=$(echo "$con_object" | jq -r '.REGISTRY_NAME')
+        rgname=$(echo "$con_object" | jq -r '.WEB_APP_RG_NAME')
+        udmid=$(echo "$con_object" | jq -r '.USER_MANAGED_ID')
+        appserviceplan=$(echo "$con_object" | jq -r '.APP_PLAN_NAME')
+        appserviceweb=$(echo "$con_object" | jq -r '.WEB_APP_NAME')
+        acr_rg=$(echo "$con_object" | jq -r '.REGISTRY_RG_NAME')
+        websku=$(echo "$con_object" | jq -r '.WEB_APP_SKU')
+
+        read -r -a connection_names <<< "$(echo "$con_object" | jq -r '.CONNECTION_NAMES | join(" ")')"
+        echo $connection_names
+
+        az group create --name $rgname --location westeurope
+        
+        az identity create --name $udmid --resource-group $rgname
+        sleep 15
+        principalId=$(az identity show --resource-group $rgname \
+          --name $udmid --query principalId --output tsv)
+        
+        registryId=$(az acr show --resource-group $acr_rg \
+          --name $REGISTRY_NAME --query id --output tsv)
+        az role assignment create --assignee $principalId --scope $registryId --role "AcrPull"
+        az appservice plan create --name $appserviceplan --resource-group $rgname --is-linux --sku $websku
+
+        az webapp create --resource-group $rgname --plan $appserviceplan --name $appserviceweb --deployment-container-image-name \
+          $REGISTRY_NAME.azurecr.io/${{ github.event.inputs.FLOW_TO_EXECUTE }}_${{ github.event.inputs.DEPLOY_ENVIRONMENT }}:$(Build.BuildNumber)
+
+        az webapp config appsettings set --resource-group $rgname --name $appserviceweb --settings WEBSITES_PORT=8080
+
+        for name in "${connection_names[@]}"; do
+        api_key=$(echo '${{ github.event.inputs.CONNECTION_DETAILS }}' | jq -r --arg name "$name" '.[] | select(.name == $name) | .api_key')
+          uppercase_name="${name^^}"
+          modified_name="${uppercase_name}_API_KEY"
+          az webapp config appsettings set --resource-group $rgname --name $appserviceweb --settings $modified_name=$api_key
+        done
+
+        id=$(az identity show --resource-group $rgname --name $udmid --query id --output tsv)
+
+        az webapp identity assign --resource-group $rgname --name $appserviceweb --identities $id
+
+        appConfig=$(az webapp config show --resource-group $rgname --name $appserviceweb --query id --output tsv)
+
+        az resource update --ids $appConfig --set properties.acrUseManagedIdentityCreds=True
+
+        clientId=$(az identity show --resource-group $rgname --name $udmid --query clientId --output tsv)
+
+        az resource update --ids $appConfig --set properties.AcrUserManagedIdentityID=$clientId
+
+
