CD jenkins pipeline test params-check

diff --git a/.jenkins/jobs/webapp_deployment b/.jenkins/jobs/webapp_deployment
--- a/.jenkins/jobs/webapp_deployment
+++ b/.jenkins/jobs/webapp_deployment
@@ -1,60 +1,84 @@
-pipeline {
-    agent any
-    parameters {
-        string(name: 'flow_to_execute', defaultValue: 'named_entity_recognition', description: 'The flow use-case to execute')
-        string(name: 'deploy_environment', defaultValue: 'dev', description: 'Execution Environment')
-    }
+#!/bin/bash
 
-    environment {
-        dev_connections = credentials('COMMON_DEV_CONNECTIONS')
-        registry_details = credentials('DOCKER_IMAGE_REGISTRY')
-    }
+# Description: 
+# This script generates docker image for Prompt flow deployment
+set -e # fail on error
 
-    stages {
+echo "Arguments"
+echo $@
+# read values from llmops_config.json related to given environment
+config_path="./$flow_to_execute/llmops_config.json"
+env_name=$deploy_environment
+selected_object=$(jq ".envs[] | select(.ENV_NAME == \"$env_name\")" "$config_path")
 
-    stage('Create local promptflow connections') {
-            steps {
-                withCredentials([azureServicePrincipal('AZURE_CREDENTIALS')]) {
-                    withPythonEnv('/usr/bin/python3.9') {
-                    sh '''
-                    python -m pip install -r .jenkins/requirements/execute_job_requirements.txt
-                    python -m pip install -r .jenkins/requirements/build_validation_requirements.txt
-                    python -m llmops.common.prompt_local_connections \\
-                    --flow_to_execute ${flow_to_execute} \\
-                    --env_name ${deploy_environment} \\
-                    --connection_details "$dev_connections"
-                    '''
-                }
-            }
-            }
-        }
+if [[ -n "$selected_object" ]]; then
+    STANDARD_FLOW=$(echo "$selected_object" | jq -r '.STANDARD_FLOW_PATH')
+        
+    pf flow build --source "./$flow_to_execute/$STANDARD_FLOW" --output "./$flow_to_execute/docker"  --format docker 
 
-    stage('Create Docker Image') {
-            steps {
-            withCredentials([string(credentialsId: 'DOCKER_IMAGE_REGISTRY', variable: 'registry_details'),
-            string(credentialsId: 'COMMON_DEV_CONNECTIONS', variable: 'connection_details')]) {
-            withPythonEnv('/usr/bin/python3.9') {
-                sh """
-                    python -m pip install -r .jenkins/requirements/build_validation_requirements.txt
-                    # Your Docker image creation command here
-                    echo "build no script:"
-                    echo ${BUILD_NUMBER}
-                    #!/bin/bash
-                    ./llmops/common/scripts/gen_docker_image.sh --flow_to_execute $flow_to_execute --deploy_environment $deploy_environment --build_id ${BUILD_NUMBER} --REGISTRY_DETAILS '${registry_details}' --CONNECTION_DETAILS '${connection_details}'
-                """
-            }
-            }
-            }
-        }
+    cp "./$flow_to_execute/environment/Dockerfile" "./$flow_to_execute/docker/Dockerfile"
 
-        stage('Create Webapp') {
-         steps {
-         withCredentials([string(credentialsId: 'COMMON_DEV_CONNECTIONS', variable: 'connection_details')]) {
-         sh """
-                /bin/bash ./llmops/common/scripts/az_webapp_deploy.sh --flow_to_execute $flow_to_execute --deploy_environment $deploy_environment --build_id ${BUILD_NUMBER} --CONNECTION_DETAILS '${connection_details}'
-            """
-         }
-         }
-        }
-    }
-}
+    # docker build the prompt flow based image
+    docker build -t localpf "./$flow_to_execute/docker" --no-cache
+        
+    docker images
+
+    deploy_config="./$flow_to_execute/configs/deployment_config.json"
+    con_object=$(jq ".webapp_endpoint[] | select(.ENV_NAME == \"$env_name\")" "$deploy_config")
+
+    read -r -a connection_names <<< "$(echo "$con_object" | jq -r '.CONNECTION_NAMES | join(" ")')"
+    echo $connection_names
+    result_string=""
+
+    for name in "${connection_names[@]}"; do
+        api_key=$(echo $connection_details | jq -r --arg name "$name" '.[] | select(.name == $name) | .api_key')
+        uppercase_name=$(echo "$name" | tr '[:lower:]' '[:upper:]')
+        modified_name="${uppercase_name}_API_KEY"
+        result_string+=" -e $modified_name=$api_key"
+    done
+
+    docker_args=$result_string
+    docker_args+=" -m 512m --memory-reservation=256m --cpus=2 -dp 8080:8080 localpf:latest"
+
+    ##uncomment
+    #docker run $(echo "$docker_args")
+
+    #sleep 15
+
+    #docker ps -a
+        
+    #chmod +x "./$flow_to_execute/sample-request.json"
+        
+    #file_contents=$(<./$flow_to_execute/sample-request.json)
+    #echo "$file_contents"
+        
+    #python -m llmops.common.deployment.test_local_flow \
+            #--flow_to_execute $flow_to_execute
+
+    #echo
+    echo "registry details"
+    echo $registry_details
+    echo "build no"
+    echo $build_id
+    echo "connection details"
+    echo $connection_details
+
+
+    REGISTRY_NAME=$(echo "$con_object" | jq -r '.REGISTRY_NAME')
+
+    registry_object=$(echo $registry_details | jq -r --arg name "$REGISTRY_NAME" '.[] | select(.registry_name == $name)')
+    registry_server=$(echo "$registry_object" | jq -r '.registry_server')
+    registry_username=$(echo "$registry_object" | jq -r '.registry_username')
+    registry_password=$(echo "$registry_object" | jq -r '.registry_password')
+    registry_password=$(echo "$registry_object" | jq -r '.registry_password')
+
+    echo "docker push details"
+    echo $registry_server
+    echo $registry_username
+    docker login "$registry_server" -u "$registry_username" --password-stdin <<< "$registry_password"
+    docker tag localpf "$registry_server"/"$flow_to_execute"_"$deploy_environment":"latest"
+    docker push "$registry_server"/"$flow_to_execute"_"$deploy_environment":"latest"
+        
+    else
+        echo "Object in config file not found"
+    fi
