test new features

diff --git a/.azure-pipelines/templates/prepare_docker_image.yml b/.azure-pipelines/templates/prepare_docker_image.yml
--- a/.azure-pipelines/templates/prepare_docker_image.yml
+++ b/.azure-pipelines/templates/prepare_docker_image.yml
@@ -38,4 +38,54 @@ steps:
     scriptType: bash
     scriptLocation: inlineScript
     inlineScript: |
-      
+      set -e # fail on error
+      config_path="./${{ parameters.flow_to_execute }}/llmops_config.json"
+      env_name=${{ parameters.DEPLOY_ENVIRONMENT }}
+      selected_object=$(jq ".envs[] | select(.ENV_NAME == \"$env_name\")" "$config_path")
+
+      if [[ -n "$selected_object" ]]; then
+        echo "$selected_object"
+        STANDARD_FLOW=$(echo "$selected_object" | jq -r '.STANDARD_FLOW_PATH')
+        
+        pf flow build --source "./${{ parameters.flow_to_execute }}/$STANDARD_FLOW" --output "./${{ parameters.flow_to_execute }}/docker"  --format docker 
+        ls ./${{ parameters.flow_to_execute }}/docker
+        ls ./${{ parameters.flow_to_execute }}/docker/connections
+        ls ./${{ parameters.flow_to_execute }}/docker/flow
+        mv "./${{ parameters.flow_to_execute }}/environment/Dockerfile" "./${{ parameters.flow_to_execute }}/docker/Dockerfile"
+        cat "./${{ parameters.flow_to_execute }}/docker/Dockerfile"
+
+        docker build -t localpf "./${{ parameters.flow_to_execute }}/docker" --no-cache
+        
+        docker images
+        deploy_config="./${{ parameters.flow_to_execute }}/configs/deployment_config.json"
+        webapp_object=$(jq ".webapp_endpoint[] | select(.ENV_NAME == \"$env_name\")" "$deploy_config")
+        echo "$webapp_object"
+        CONNECTION_NAME=$(echo "$webapp_object" | jq -r '.AOAI_CONNECTION_NAMES[]')
+        result_string=""
+
+        for name in "${CONNECTION_NAME[@]}"; do
+            api_key=$(echo '${{ parameters.CONNECTION_DETAILS }}' | jq -r --arg name "$name" '.[] | select(.name == $name) | .api_key')
+            uppercase_name="${name^^}"
+            modified_name="${uppercase_name}_API_KEY"
+            result_string+=" -e $modified_name=$api_key"
+        done
+
+        echo "$result_string"
+
+        IFS=' ' read -r -a docker_args <<< "$result_string"
+
+        docker_args+=(-m 512m --memory-reservation=256m --cpus=2 -dp 8080:8080 localpf:latest )
+
+        docker run "${docker_args[@]}"
+
+        sleep 30
+        docker ps -a
+        chmod +x "./${{ parameters.flow_to_execute }}/sample-request.json" 
+        file_contents=$(<./${{ parameters.flow_to_execute }}/sample-request.json)
+        echo "$file_contents"
+        python -m llmops.common.deployment.test_local_flow \
+                --flow_to_execute ${{ parameters.flow_to_execute }}
+
+      else
+        echo "Object in config file not found"
+      fi
