test new features

diff --git a/.azure-pipelines/templates/prepare_docker_image.yml b/.azure-pipelines/templates/prepare_docker_image.yml
--- a/.azure-pipelines/templates/prepare_docker_image.yml
+++ b/.azure-pipelines/templates/prepare_docker_image.yml
@@ -8,7 +8,8 @@ parameters:
 - name: REGISTRY_DETAILS
   type: string
 steps:
-- template: configure_azureml_agent.yml
+- template: ./configure_azureml_agent.yml
+
 - template: execute_python_code.yml
   parameters:
     step_name: "Create local Connection"
@@ -18,15 +19,82 @@ steps:
         --flow_to_execute ${{ parameters.flow_to_execute }} \
         --connection_details '${{ parameters.CONNECTION_DETAILS }}'
 
-- task: Bash@3
+- task: AzureCLI@2
   displayName: Build Docker Image with flow artifacts
   continueOnError: false
   inputs: 
-    targetType: filePath
-    filePath: ./llmops/common/scripts/gen_docker_image.sh
-  env:
-    flow_to_execute: ${{ parameters.flow_to_execute }}
-    deploy_environment: ${{ parameters.DEPLOY_ENVIRONMENT }}
-    connection_details: ${{ parameters.CONNECTION_DETAILS }}
-    registry_details: ${{ parameters.REGISTRY_DETAILS }}
+    azureSubscription: $(AZURE_RM_SVC_CONNECTION)
+    scriptType: bash
+    scriptLocation: scriptPath
+    inlineScript: |
+      set -e # fail on error
+      config_path="./${{ parameters.flow_to_execute }}/llmops_config.json"
+      env_name=${{ parameters.DEPLOY_ENVIRONMENT }}
+      selected_object=$(jq ".envs[] | select(.ENV_NAME == \"$env_name\")" "$config_path")
 
+      if [[ -n "$selected_object" ]]; then
+        STANDARD_FLOW=$(echo "$selected_object" | jq -r '.STANDARD_FLOW_PATH')
+        
+        pf flow build --source "./${{ parameters.flow_to_execute }}/$STANDARD_FLOW" \
+          --output "./${{ parameters.flow_to_execute }}/docker"  --format docker 
+
+        mv "./${{ parameters.flow_to_execute }}/environment/Dockerfile" \
+          "./${{ parameters.flow_to_execute }}/docker/Dockerfile"
+
+        docker build -t localpf "./${{ parameters.flow_to_execute }}/docker" --no-cache
+        
+        docker images
+
+        deploy_config="./${{ parameters.flow_to_execute }}/configs/deployment_config.json"
+        con_object=$(jq ".webapp_endpoint[] | select(.ENV_NAME == \"$env_name\")" "$deploy_config")
+
+        read -r -a connection_names <<< "$(echo "$con_object" | jq -r '.CONNECTION_NAMES | join(" ")')"
+        echo $connection_names
+        result_string=""
+
+        for name in "${connection_names[@]}"; do
+            api_key=$(echo '${{ parameters.CONNECTION_DETAILS }}' \
+              | jq -r --arg name "$name" '.[] \
+              | select(.name == $name) \
+              | .api_key')
+            uppercase_name="${name^^}"
+            modified_name="${uppercase_name}_API_KEY"
+            result_string+=" -e $modified_name=$api_key"
+        done
+
+        IFS=' ' read -r -a docker_args <<< "$result_string"
+        docker_args+=(-m 512m --memory-reservation=256m --cpus=2 -dp 8080:8080 localpf:latest )
+        docker run "${docker_args[@]}"
+
+        sleep 15
+
+        docker ps -a
+        
+        chmod +x "./${{ parameters.flow_to_execute }}/sample-request.json" 
+        
+        file_contents=$(<./${{ parameters.flow_to_execute }}/sample-request.json)
+        echo "$file_contents"
+        
+        python -m llmops.common.deployment.test_local_flow \
+                --flow_to_execute ${{ parameters.flow_to_execute }}
+
+        REGISTRY_NAME=$(echo "$con_object" | jq -r '.REGISTRY_NAME')
+
+        registry_object=$(echo '${{ parameters.REGISTRY_DETAILS }}' \
+          | jq -r --arg name "$REGISTRY_NAME" '.[] \
+          | select(.registry_name == $name)')
+        register_server=$(echo "$registry_object" | jq -r '.register_server')
+        registry_username=$(echo "$registry_object" | jq -r '.registry_username')
+        registry_password=$(echo "$registry_object" | jq -r '.registry_password')
+
+
+        docker login "$register_server" -u "$registry_username" \
+          --password-stdin <<< "$registry_password" 
+        docker tag localpf \
+          "$register_server"/${{ parameters.flow_to_execute }}_${{ parameters.DEPLOY_ENVIRONMENT }}:$(Build.BuildNumber)
+        docker push \
+          "$register_server"/${{ parameters.flow_to_execute }}_${{ parameters.DEPLOY_ENVIRONMENT }}:$(Build.BuildNumber)
+        
+      else
+        echo "Object in config file not found"
+      fi
