Update platform_ci_dev_workflow.yml

diff --git a/.github/workflows/platform_ci_dev_workflow.yml b/.github/workflows/platform_ci_dev_workflow.yml
--- a/.github/workflows/platform_ci_dev_workflow.yml
+++ b/.github/workflows/platform_ci_dev_workflow.yml
@@ -54,8 +54,10 @@ jobs:
 
       - name: Create .env file
         run: |
+          set -e # fail on error        
           echo "${{ secrets.ENV_VARS }}" >> .env
           for var in $(cat .env); do
+            echo "::add-mask::$var"
             echo "$var" >> $GITHUB_ENV
           done
       - name: load .env file
